[package]
name = "fugue-box"
version = "0.0.1"
edition = "2021"
authors = ["MagicalLiebe <magical.liebe@gmail.com>"]
description = "A CLI tool to easily move files, copy & paste and create symbolic links."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.17", features = ["derive"] }
serde = "^1.0"
serde_derive = "^1.0"
confy = "^0.4"
dirs = "4.0.0"
termion = "1.5.6"

[[bin]]
name = "fugue"
path = "src/main.rs"